### ISSUE TITLE
Copier operation uses local cache when dst file path exists

### ISSUE THREAD

**Issue by bokket** [beyondstorage/go-service-hdfs#17]
When dst file path exists, I think we can copy to local and then to remote
Code like

```
                str,err:=os.Getwd()
		if err!=nil {
			return err
		}

		err=s.hdfs.CopyToLocal(rs,str+filepath.Base(rd))
		if err!=nil {
			return err
		}

		err = s.hdfs.Remove(rd)
		if err != nil && errors.Is(err, os.ErrNotExist) {
			err = nil
		}

		err=s.hdfs.CopyToRemote(str+filepath.Base(rd),rd)
		if err!=nil {
			return err
		}
		return err
```
But this creates multiple local files.
Possible solutions

- Caching in the current directory.So that we don't take up space when copying the same file.
- Or generate a `.cache` file in home directory.

Or other ways?

**Comment by Xuanwo** [comment]
If the service doesn't have the native support for `Copy`, we don't need to implement it, leave it for the user to decide.

For example, it's simple to implement via:

```
w, r := io.Pipe()
_, _ = store.Read("xxx", w)
_, _ = store.Write("yyy", r, size)
```

**Comment by bokket** [comment]
> 如果服务没有对​​ 的原生支持`Copy`，我们不需要实现它，让用户来决定。
> 
> 例如，通过以下方式实现很简单：
> 
> ```
> w, r := io.Pipe()
> _, _ = store.Read("xxx", w)
> _, _ = store.Write("yyy", r, size)
> ```

Ok，I will explain in the document at the end.Close this iusse.
