### ISSUE TITLE
HDFS does not have the Context's method inside the storage delete operation

### ISSUE THREAD

**Issue by bokket** [beyondstorage/go-service-hdfs#8]
Storage delete unified function signature is `func (s *Storage) delete(ctx context.Context, path string, opt pairStorageDelete) (err error)`
But hdfs only simple `func (c *Client) Remove(name string) error` [method](https://pkg.go.dev/github.com/colinmarc/hdfs#Client.Remove)
so there are only three ways to solve

1. to the upstream requirements, but the response is very slow
2. take their own rpc structure for communication, need some time to test to maintain correctness
3. temporarily use the function signature of `func (s *Storage) delete(path string, opt pairStorageDelete) (err error)`

**Comment by Xuanwo** [comment]
Just ignore the input `context` is OK. Leave a comment for a decription.

**Comment by bokket** [comment]
hdfs some places and Storage standards are a bit large
Do we need to record every one of them?

**Comment by Xuanwo** [comment]
> hdfs some places and Storage standards are a bit large
> Do we need to record every one of them?

Yes, we need to. We can add them both in docs and comments.

**Comment by Xuanwo** [comment]
Maybe we could add an RFC in this repo for reference? Like https://github.com/beyondstorage/beyond-fs/pull/5

**Comment by bokket** [comment]
> Maybe we could add an RFC in this repo for reference? Like [beyondstorage/beyond-fs#5](https://github.com/beyondstorage/beyond-fs/pull/5)

How do we design it?
It looks like it wants to be stored in BFS memory first and then unified according to storage
